# Site settings
title:       Ventuso
email:       support@ventuso.net
author:      
description: ""
baseurl:     ""
url:         "localhost"

# Google analytics
google_analytics:

# Optional features
animated:           false
show_related_posts: false
show_post_footers:  false

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname:

# Social icons
show_social_icons: false
github_username: ventuso
stackoverflow_id:
twitter_username:
google_plus_id:
linkedin_username:
angellist_username:
bitcoin_url:
paypal_url:
flattr_button:

# Post sharing icons
show_sharing_icons: false
share_text: 'Share this post!'
# Change to 'true' to enable individual icons
share_facebook: true
share_twitter: true
share_googleplus: true
share_linkedin: false
share_digg: false
share_tumblr: true
share_reddit: true
share_stumbleupon: false
share_hackernews: false

# Build settings
markdown:     redcarpet
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    pretty
paginate:     3
highlighter:     true
sass:
  compressed: true

github:
  repo:           https://github.com/poole/lanyon

# Tagging
#tag_page_layout: tag_page
#tag_page_dir: tag
#tag_permalink_style: pretty
#ignored_tags: []

# Gems
gems: [jekyll-paginate,rb-fsevent]
paginate: 5
paginate_path: "page:num"